name: todo_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  buttons_tabbar: ^1.3.3
  flutter_localizations:
    sdk: flutter
  roundcheckbox: ^2.0.4+1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/icon/todo_logo.png"
  #   android: "launcher_icon"
  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
